GET  http://localhost/workspaces

###
POST http://localhost/workspace/save
Content-Type: application/json

{
    "name":"Jeferson",
    "kind":"SITE",
    "description":"Criado"
    
}
###
GET  http://localhost/workspace/1

###
DELETE  http://localhost/workspace/3